using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.SqlClient;
using System.Reflection;
using System.Text;

using LEADBase;

namespace LEAD
{
	/// <summary>
	/// Class Name: ContactAddress
	/// This class can be modified by the user and will not be written over if the class is already found.
	/// Generated by GenClasses on 04/06/2017 01:40 PM
	/// </summary>
	public partial class ContactAddress
	{
		public string SingleLineAddress
		{
			get
			{
				string rtv = string.Empty;
				rtv = (_address != string.Empty ? _address + ", " : string.Empty) +
					(_city != string.Empty ? _city + ", " : string.Empty) +
					(_state != string.Empty ? _state + ", " : string.Empty) +
					(_zip != string.Empty ? _zip : string.Empty) +
					(_zipPlus4 != string.Empty ? "-" + _zipPlus4 : string.Empty);
				return rtv;
			}
		}
		public static readonly string FN_SingleLineAddress = "SingleLineAddress";

		public string MultiLineAddress
		{
			get
			{
				string rtv = string.Empty;
				rtv = (_address != string.Empty ? _address + Environment.NewLine : string.Empty) +
					(_city != string.Empty ? _city + ", " : string.Empty) +
					(_state != string.Empty ? _state + ", " : string.Empty) +
					(_zip != string.Empty ? _zip : string.Empty) +
					(_zipPlus4 != string.Empty ? "-" + _zipPlus4 : string.Empty);
				return rtv;
			}
		}
		public static readonly string FN_MultiLineAddress = "MultiLineAddress";
	}

	public partial class ContactAddressCollection : ClassGenBindingList<ContactAddress, long>
	{
	}
}

