using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.SqlClient;
using System.Reflection;
using System.Text;

using LEADBase;

namespace LEAD
{
	/// <summary>
	/// Class Name: Search_Personnel_GenderCount
	/// This class can be modified by the user and will not be written over if the class is already found.
	/// Generated by GenClasses on 06/29/2017 07:10 AM
	/// </summary>
	public partial class Search_Personnel_GenderCount
	{
	}

	public partial class Search_Personnel_GenderCountCollection : ClassGenBindingList<Search_Personnel_GenderCount, string>
	{
	}
}

