using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.SqlClient;
using System.Reflection;
using System.Text;

using LEADBase;

namespace LEAD
{
	/// <summary>
	/// Class Name: SecGroup
	/// This class can be modified by the user and will not be written over if the class is already found.
	/// Generated by GenClasses on 04/06/2017 01:40 PM
	/// </summary>
	public partial class SecGroup
	{
	}

	public partial class SecGroupCollection : ClassGenBindingList<SecGroup, long>
	{
	}
}

