using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.SqlClient;
using System.Reflection;
using System.Text;

using LEADBase;

namespace LEAD
{
	/// <summary>
	/// Class Name: Search_Contact_PhoneList
	/// Generated by GenClasses v.4.0.0 on 07/28/2017 05:18 AM
	/// </summary>
	#region Search_Contact_PhoneList Class
	[Serializable]
	public partial class Search_Contact_PhoneList : LEAD_BaseObject, 
		IClassGenLogXML, IClassGenCopyWithNewID, IClassGenPropertyChanging, INotifyPropertyChanging
	{
		#region Private Properties
		private long _contactID = 0;
		private long _agencyID = 0;
		private string _lastName = null;
		private string _firstName = null;
		private string _fullName_LastFirst = null;
		private string _homePhone = null;
		private string _otherPhone = null;
		private string _pagerPhone = null;
		private string _cellPhone = null;
		private string _workPhone = null;

		private bool _disposed = false;
		#endregion Private Properties

		#region Constructors

		/// <summary>
		/// Creates a new Search_Contact_PhoneList.
		/// </summary>
		public Search_Contact_PhoneList()
		{
			SetBaseRules();				// Set the base rules
			SetAdditionalRules();		// Set any additional rules
		}

		// Secondary constructor omitted.
		// To generate a secondary constructor, add a primary key to the table.

		#endregion Constructors

		#region Disposal
		/// <summary>
		/// Override of the disposal method
		/// </summary>
		/// <param name="disposing">True if the object is being disposed, otherwise false</param>
		protected override void Dispose(bool disposing)
		{
			if (!this._isDisposable) { return; }

			if (!this._disposed)
			{
				try
				{
					// Set the disposed on this object to true
					this._disposed = true;

					if (disposing)
					{
						// Release the managed resources you added in
						// this derived class here.

					}

					// Release the native unmanaged resources you added
					// in this derived class here.
					// <No Unmanaged Resources in this block>
				}
				finally
				{
					// Call Dispose on your base class.
					if (this.IsDisposable) { base.Dispose(disposing); }
				}
			}
		}
		#endregion Disposal
		
		#region Public Properties
		/// <summary>
		/// Property generated from the iContactID field.
		/// </summary>
		public long ContactID
		{
			get 
			{
				if (RefreshRate != RefreshFrequency.ByDeveloperOnly) { RefreshObject(); }
				return _contactID;
			}
			set 
			{
				if (_contactID != value)
				{
					bool cancelled = NotifyPropertyChanging("ContactID", _contactID, value);
					if (!cancelled)
					{
						_contactID = value;
						SetModifiedStatus("ContactID");
						NotifyPropertyChanged("ContactID", value);
					}
				}
			}
		}

		/// <summary>
		/// Property generated from the iAgencyID field.
		/// </summary>
		public long AgencyID
		{
			get 
			{
				if (RefreshRate != RefreshFrequency.ByDeveloperOnly) { RefreshObject(); }
				return _agencyID;
			}
			set 
			{
				if (_agencyID != value)
				{
					bool cancelled = NotifyPropertyChanging("AgencyID", _agencyID, value);
					if (!cancelled)
					{
						_agencyID = value;
						SetModifiedStatus("AgencyID");
						NotifyPropertyChanged("AgencyID", value);
					}
				}
			}
		}

		/// <summary>
		/// Property generated from the sLastName field.
		/// </summary>
		public string LastName
		{
			get 
			{
				if (RefreshRate != RefreshFrequency.ByDeveloperOnly) { RefreshObject(); }
				return _lastName;
			}
			set 
			{
				if (_lastName != value)
				{
					bool cancelled = NotifyPropertyChanging("LastName", _lastName, value);
					if (!cancelled)
					{
						_lastName = value;
						SetModifiedStatus("LastName");
						NotifyPropertyChanged("LastName", value);
					}
				}
			}
		}

		/// <summary>
		/// Property generated from the sFirstName field.
		/// </summary>
		public string FirstName
		{
			get 
			{
				if (RefreshRate != RefreshFrequency.ByDeveloperOnly) { RefreshObject(); }
				return _firstName;
			}
			set 
			{
				if (_firstName != value)
				{
					bool cancelled = NotifyPropertyChanging("FirstName", _firstName, value);
					if (!cancelled)
					{
						_firstName = value;
						SetModifiedStatus("FirstName");
						NotifyPropertyChanged("FirstName", value);
					}
				}
			}
		}

		/// <summary>
		/// Property generated from the sFullName_LastFirst field.
		/// </summary>
		public string FullName_LastFirst
		{
			get 
			{
				if (RefreshRate != RefreshFrequency.ByDeveloperOnly) { RefreshObject(); }
				return _fullName_LastFirst;
			}
			set 
			{
				if (_fullName_LastFirst != value)
				{
					bool cancelled = NotifyPropertyChanging("FullName_LastFirst", _fullName_LastFirst, value);
					if (!cancelled)
					{
						_fullName_LastFirst = value;
						SetModifiedStatus("FullName_LastFirst");
						NotifyPropertyChanged("FullName_LastFirst", value);
					}
				}
			}
		}

		/// <summary>
		/// Property generated from the sHomePhone field.
		/// </summary>
		public string HomePhone
		{
			get 
			{
				if (RefreshRate != RefreshFrequency.ByDeveloperOnly) { RefreshObject(); }
				return _homePhone;
			}
			set 
			{
				if (_homePhone != value)
				{
					bool cancelled = NotifyPropertyChanging("HomePhone", _homePhone, value);
					if (!cancelled)
					{
						_homePhone = value;
						SetModifiedStatus("HomePhone");
						NotifyPropertyChanged("HomePhone", value);
					}
				}
			}
		}

		/// <summary>
		/// Property generated from the sOtherPhone field.
		/// </summary>
		public string OtherPhone
		{
			get 
			{
				if (RefreshRate != RefreshFrequency.ByDeveloperOnly) { RefreshObject(); }
				return _otherPhone;
			}
			set 
			{
				if (_otherPhone != value)
				{
					bool cancelled = NotifyPropertyChanging("OtherPhone", _otherPhone, value);
					if (!cancelled)
					{
						_otherPhone = value;
						SetModifiedStatus("OtherPhone");
						NotifyPropertyChanged("OtherPhone", value);
					}
				}
			}
		}

		/// <summary>
		/// Property generated from the sPagerPhone field.
		/// </summary>
		public string PagerPhone
		{
			get 
			{
				if (RefreshRate != RefreshFrequency.ByDeveloperOnly) { RefreshObject(); }
				return _pagerPhone;
			}
			set 
			{
				if (_pagerPhone != value)
				{
					bool cancelled = NotifyPropertyChanging("PagerPhone", _pagerPhone, value);
					if (!cancelled)
					{
						_pagerPhone = value;
						SetModifiedStatus("PagerPhone");
						NotifyPropertyChanged("PagerPhone", value);
					}
				}
			}
		}

		/// <summary>
		/// Property generated from the sCellPhone field.
		/// </summary>
		public string CellPhone
		{
			get 
			{
				if (RefreshRate != RefreshFrequency.ByDeveloperOnly) { RefreshObject(); }
				return _cellPhone;
			}
			set 
			{
				if (_cellPhone != value)
				{
					bool cancelled = NotifyPropertyChanging("CellPhone", _cellPhone, value);
					if (!cancelled)
					{
						_cellPhone = value;
						SetModifiedStatus("CellPhone");
						NotifyPropertyChanged("CellPhone", value);
					}
				}
			}
		}

		/// <summary>
		/// Property generated from the sWorkPhone field.
		/// </summary>
		public string WorkPhone
		{
			get 
			{
				if (RefreshRate != RefreshFrequency.ByDeveloperOnly) { RefreshObject(); }
				return _workPhone;
			}
			set 
			{
				if (_workPhone != value)
				{
					bool cancelled = NotifyPropertyChanging("WorkPhone", _workPhone, value);
					if (!cancelled)
					{
						_workPhone = value;
						SetModifiedStatus("WorkPhone");
						NotifyPropertyChanged("WorkPhone", value);
					}
				}
			}
		}
		#endregion Public Properties

		#region Public Methods
		/// <summary>
		/// Set the Base Rules on the class.
		/// </summary>
		public void SetBaseRules()
		{
			// Property Required Rules
			this.Rules.Add(new PropertyRequiredCustomRule("ContactID", "The \"Contact ID\" field is required in the Search_Contact_PhoneList record."));
			this.Rules.Add(new PropertyRequiredCustomRule("AgencyID", "The \"Agency ID\" field is required in the Search_Contact_PhoneList record."));

			// Max Length Rules
			this.Rules.Add(new MaxLengthCustomRule("LastName", 100, "The maximum length for the \"LastName\" field is 100 characters."));
			this.Rules.Add(new MaxLengthCustomRule("FirstName", 100, "The maximum length for the \"FirstName\" field is 100 characters."));
			this.Rules.Add(new MaxLengthCustomRule("FullName_LastFirst", 200, "The maximum length for the \"FullName_LastFirst\" field is 200 characters."));
		}

		/// <summary>
		/// Clone the object as a new instance and pass it back.
		/// </summary>
		/// <returns>A copy of the object.</returns>
		public Search_Contact_PhoneList Clone()
		{
			Search_Contact_PhoneList item = base.CloneObjectWithIL<Search_Contact_PhoneList>(this);

			return item;
		}

		/// <summary>
		/// Copy the object - then change the ID field to a new value.
		/// </summary>
		/// <returns>A copy of the object with a new ID.</returns>
		public object CopyWithNewID()
		{
			// Make the copy of the object
			Search_Contact_PhoneList item = this.Clone();
			
			// Change the ID field

			// Reset the record status to new
			item.RecordStatus = RecordStatus.New;

			return item;
		}

		
		/// <summary>
		/// Refresh the object based on the threshhold of set minutes on the object.
		/// </summary>
		/// <param name="threshHoldInMinutes">The threshhold in minutes that is allowed before a record is marked as "old".</param>
		/// <returns>A collection of any exceptions that were raised in the method.</returns>
		public ClassGenExceptionCollection RefreshObject(int threshHoldInMinutes)
		{
			ClassGenExceptionCollection errors = new ClassGenExceptionCollection();

			// Find out how far back you need to go based on the passed threshhold
			if (_dateTimeObjectPopulated == null) { return errors; }
			DateTime currentTime = DAL.GetSQLServerDateTime();
			if (((TimeSpan)currentTime.Subtract(_dateTimeObjectPopulated.Value)).TotalMinutes > threshHoldInMinutes)
			{
				// Force a refresh on the object
				errors.AddRange(this.Get());
			}

			return errors;		// Return the collection
		}

		/// <summary>
		/// Refresh the object based on the currently set Refresh on the project.
		/// </summary>
		/// <returns>A collection of any exceptions that were raised in the method.</returns>
		public ClassGenExceptionCollection RefreshObject()
		{
			return RefreshObject((int)RefreshRate);
		}

		/// <summary>
		/// Force a Refresh on the object based on the held Primary Key GUID.
		/// </summary>
		/// <returns>A collection of any exceptions that were raised in the method.</returns>
		public ClassGenExceptionCollection RefreshForce()
		{
			ClassGenExceptionCollection errors = new ClassGenExceptionCollection();

			// I would really have liked to have generated the code for you for this method.
			// But again, since you don't have a key field for this class, I can't.  Check 
			// the Constructors section at the top of this document for more information.

			return errors;		// Return the collection
		}

		/// <summary>
		/// Get the record specified on the Key Fields in the table.
		/// Code block could not be generated due to no primary key selected in table.
		/// </summary>
		/// <param name="includeParentPopulation">Whether or not to include values derived from a parent table.</param>
		public ClassGenExceptionCollection Get(bool includeParentPopulation)
		{
			ClassGenExceptionCollection errors = new ClassGenExceptionCollection();

			// Code omitted due to missing primary key(s).
			// See Constructors region for more information.

			return errors;		// Return the error collection
		}

		/// <summary>
		/// Get the record specified based on the Key Fields in the table
		/// Code block could not be generated due to no primary key selected in table.
		/// </summary>
		/// <returns>A collection of exceptions that occurred while trying to perform the Get.</returns>
		public ClassGenExceptionCollection Get()
		{
			return Get(false);		// Get the item
		}

		/// <summary>
		/// Populate the object using the datarow passed in...
		/// </summary>
		/// <param name="row">The DataRow to populate the object from.</param>
		/// <param name="includeParentPopulation">Whether to include data generated from parent tables.</param>
		/// <returns>A collection of exceptions that occurred while trying to perform the Get.</returns>
		public ClassGenExceptionCollection Get(DataRow row, bool includeParentPopulation)
		{
			ClassGenExceptionCollection errors = new ClassGenExceptionCollection();

			try
			{
				// Enumerate through the fields and set up the object
				_recordStatus = RecordStatus.Current;
				_isLoaded = false;
				if (row.Table.Columns.Contains("dateTimeObjectPopulated"))
				{
					_dateTimeObjectPopulated = (DateTime)row["dateTimeObjectPopulated"];
				}
				else
				{
					_dateTimeObjectPopulated = DateTime.Now;
				}
				DAL.EvalNumSecondsLocalMachineBehindServer(_dateTimeObjectPopulated.Value);
				
				_contactID = long.Parse(row["iContactID"] != DBNull.Value ? row["iContactID"].ToString() : "0");
				_agencyID = long.Parse(row["iAgencyID"] != DBNull.Value ? row["iAgencyID"].ToString() : "0");
				_lastName = (row["sLastName"] != DBNull.Value ? _lastName = row["sLastName"].ToString() : null);
				_firstName = (row["sFirstName"] != DBNull.Value ? _firstName = row["sFirstName"].ToString() : null);
				_fullName_LastFirst = (row["sFullName_LastFirst"] != DBNull.Value ? _fullName_LastFirst = row["sFullName_LastFirst"].ToString() : null);
				
				_homePhone = (row["sHomePhone"] != DBNull.Value ? _homePhone = row["sHomePhone"].ToString() : null);
				_otherPhone = (row["sOtherPhone"] != DBNull.Value ? _otherPhone = row["sOtherPhone"].ToString() : null);
				_pagerPhone = (row["sPagerPhone"] != DBNull.Value ? _pagerPhone = row["sPagerPhone"].ToString() : null);
				_cellPhone = (row["sCellPhone"] != DBNull.Value ? _cellPhone = row["sCellPhone"].ToString() : null);
				_workPhone = (row["sWorkPhone"] != DBNull.Value ? _workPhone = row["sWorkPhone"].ToString() : null);

				_isLoaded = true;
			}
			catch (Exception ex) { errors.Add(new ClassGenException(ex)); }

			return errors;		// Return the error collection
		}

		/// <summary>
		/// Get the record specified from the passed datarow.
		/// </summary>
		/// <param name="row">The DataRow used to determine the correct record.</param>
		/// <returns>A collection of exceptions that occurred while trying to perform the Get.</returns>
		public ClassGenExceptionCollection Get(DataRow row)
		{
			return Get(row, false);		// Get the item
		}

		/// <summary>
		/// Converts the object to a datatable. 
		/// </summary>
		/// <param name="dt">The datatable to use as a template.</param>
		/// <returns>A new datarow.</returns>
		public DataRow ToDataRow(DataTable dt)
		{
			// Generate and return a data row
			return ToDataRowWithIL<Search_Contact_PhoneList>(this, dt);
		}

		#endregion Public Methods

		#region Public Static Values

		// Main Class - Search_Contact_PhoneList

		/// <summary>
		/// The property's name as a static value.
		/// </summary>
		public static readonly string FN_ContactID = "ContactID";

		/// <summary>
		/// The property's name as a static value.
		/// </summary>
		public static readonly string FN_AgencyID = "AgencyID";

		/// <summary>
		/// The property's name as a static value.
		/// </summary>
		public static readonly string FN_LastName = "LastName";

		/// <summary>
		/// The property's name as a static value.
		/// </summary>
		public static readonly string FN_FirstName = "FirstName";

		/// <summary>
		/// The property's name as a static value.
		/// </summary>
		public static readonly string FN_FullName_LastFirst = "FullName_LastFirst";

		/// <summary>
		/// The property's name as a static value.
		/// </summary>
		public static readonly string FN_HomePhone = "HomePhone";

		/// <summary>
		/// The property's name as a static value.
		/// </summary>
		public static readonly string FN_OtherPhone = "OtherPhone";

		/// <summary>
		/// The property's name as a static value.
		/// </summary>
		public static readonly string FN_PagerPhone = "PagerPhone";

		/// <summary>
		/// The property's name as a static value.
		/// </summary>
		public static readonly string FN_CellPhone = "CellPhone";

		/// <summary>
		/// The property's name as a static value.
		/// </summary>
		public static readonly string FN_WorkPhone = "WorkPhone";

		#endregion Public Static Values

		#region Public Static Methods
		/// <summary>
		/// Get a DB Field name from the field that's passed in.
		/// </summary>
		/// <param name="field">The field type to get.</param>
		/// <returns>A list of values from the collection (sorted by value).</returns>
		public static string GetDBFieldName(Search_Contact_PhoneListField field)
		{
			string fldName = string.Empty;

			// Add the elements
			switch (field)
			{
				case Search_Contact_PhoneListField.ContactID: fldName = "iContactID"; break;
				case Search_Contact_PhoneListField.AgencyID: fldName = "iAgencyID"; break;
				case Search_Contact_PhoneListField.LastName: fldName = "sLastName"; break;
				case Search_Contact_PhoneListField.FirstName: fldName = "sFirstName"; break;
				case Search_Contact_PhoneListField.FullName_LastFirst: fldName = "sFullName_LastFirst"; break;
				case Search_Contact_PhoneListField.HomePhone: fldName = "sHomePhone"; break;
				case Search_Contact_PhoneListField.OtherPhone: fldName = "sOtherPhone"; break;
				case Search_Contact_PhoneListField.PagerPhone: fldName = "sPagerPhone"; break;
				case Search_Contact_PhoneListField.CellPhone: fldName = "sCellPhone"; break;
				case Search_Contact_PhoneListField.WorkPhone: fldName = "sWorkPhone"; break;
			}

			// Return the field name
			return fldName;
		}

		/// <summary>
		/// Get a field from the DB Field that's passed in.
		/// </summary>
		/// <param name="field">The field type to get.</param>
		/// <returns>A list of values from the collection (sorted by value).</returns>
		public static string GetDBFieldName(string field)
		{
			string fldName = null;

			// Add the elements
			if (field.ToLower() == "icontactid") { fldName = Search_Contact_PhoneListField.ContactID.ToString(); }
			else if (field.ToLower() == "iagencyid") { fldName = Search_Contact_PhoneListField.AgencyID.ToString(); }
			else if (field.ToLower() == "slastname") { fldName = Search_Contact_PhoneListField.LastName.ToString(); }
			else if (field.ToLower() == "sfirstname") { fldName = Search_Contact_PhoneListField.FirstName.ToString(); }
			else if (field.ToLower() == "sfullname_lastfirst") { fldName = Search_Contact_PhoneListField.FullName_LastFirst.ToString(); }
			else if (field.ToLower() == "shomephone") { fldName = Search_Contact_PhoneListField.HomePhone.ToString(); }
			else if (field.ToLower() == "sotherphone") { fldName = Search_Contact_PhoneListField.OtherPhone.ToString(); }
			else if (field.ToLower() == "spagerphone") { fldName = Search_Contact_PhoneListField.PagerPhone.ToString(); }
			else if (field.ToLower() == "scellphone") { fldName = Search_Contact_PhoneListField.CellPhone.ToString(); }
			else if (field.ToLower() == "sworkphone") { fldName = Search_Contact_PhoneListField.WorkPhone.ToString(); }

			// Return the field name
			return fldName;
		}

		/// <summary>
		/// The database table name.
		/// </summary>
		public static readonly string DB_TableName = "vwSearch_Contact_PhoneList"; 

		/// <summary>
		/// Get a distinct list of values based on the elements in a database table.
		/// </summary>
		/// <param name="field">The field type to get.</param>
		/// <returns>A list of values from the collection (sorted by value).</returns>
		public static List<string> GetDistinctFromDB(Search_Contact_PhoneListField field)
		{
			return GetDistinctFromDB(field, string.Empty);
		}

		/// <summary>
		/// Get a distinct list of values based on the elements in a database table.
		/// </summary>
		/// <param name="field">The field type to get.</param>
		/// <param name="whereClause">The where clause to fire against the database.</param>
		/// <returns>A list of values from the collection (sorted by value).</returns>
		public static List<string> GetDistinctFromDB(Search_Contact_PhoneListField field, string whereClause)
		{
			string fldName = GetDBFieldName(field);

			if (String.IsNullOrEmpty(fldName)) { return new List<string>(); }

			// Get the datatable
			string sql = string.Empty;
			SqlCommand cmd = null;
			DataTable dt = new DataTable();
			ClassGenExceptionCollection errors = new ClassGenExceptionCollection();
			List<string> rtv = new List<string>();

			try
			{
				sql = "SELECT DISTINCT LTRIM(RTRIM([" + fldName + "])) " +
						"FROM [vwSearch_Contact_PhoneList] " +
						"WHERE [" + fldName + "] IS NOT NULL AND LTRIM(RTRIM([" + fldName + "])) <> '' " + 
						(!String.IsNullOrEmpty(whereClause) ? "AND (" + whereClause + ") " : "") + 
						"ORDER BY LTRIM(RTRIM([" + fldName + "]))";
				cmd = new SqlCommand(sql);
				dt = DAL.SQLExecDataTable(cmd);
				if (fldName.ToLower().EndsWith("guid"))
				{
					foreach (DataRow row in dt.Rows)
					{
						rtv.Add(row[0].ToString().ToLower());
					}
				}
				else
				{
					foreach (DataRow row in dt.Rows)
					{
						rtv.Add(row[0].ToString());
					}
				}
			}
			catch (SqlException sqle) { errors.Add(new ClassGenException(sqle)); }
			catch (Exception ex) { errors.Add(new ClassGenException(ex)); }

			return rtv;
		}

		/// <summary>
		/// Get a distinct list of values based on the elements in a database table.
		/// </summary>
		/// <param name="fields">The fields to get.</param>
		/// <param name="fieldAliases">The field aliases.</param>
		/// <param name="sortedFields">The sorted fields.</param>
		/// <param name="whereClause">The where clause to fire against the database.</param>
		/// <returns>A datatable of values from the collection (sorted by value).</returns>
		public static DataTable GetDistinctFromDBAsDataTable(Search_Contact_PhoneListField[] fields, 
			string[] fieldAliases,
			Search_Contact_PhoneListField[] sortedFields, 
			string whereClause)
		{
			Dictionary<Search_Contact_PhoneListField, string> fieldNames = new Dictionary<Search_Contact_PhoneListField, string>();
			StringBuilder sbFields = new StringBuilder();
			StringBuilder sbWhereClause = new StringBuilder();
			int fieldCount = 0;
			foreach (Search_Contact_PhoneListField fld in fields)
			{
				if (!fieldNames.ContainsKey(fld))
				{
					fieldNames.Add(fld, GetDBFieldName(fld));
					sbWhereClause.Append((sbWhereClause.ToString().Trim().Length > 0 ? " AND " : " WHERE ") +
						fieldNames[fld] + " IS NOT NULL AND LTRIM(RTRIM(" + fieldNames[fld] + ")) <> '' ");
				}
				if (String.IsNullOrEmpty(fieldNames[fld])) { return null; }
				sbFields.Append((sbFields.ToString().Trim().Length > 0 ? "," : "") + "[" + fieldNames[fld] + "]" + 
					(fieldAliases.Length > fieldCount ? " AS [" + fieldAliases[fieldCount] + "] " : ""));
				fieldCount++;
			}

			Dictionary<Search_Contact_PhoneListField, string> sortedFieldNames = new Dictionary<Search_Contact_PhoneListField, string>();
			StringBuilder sbSortedFields = new StringBuilder();
			foreach (Search_Contact_PhoneListField fld in sortedFields)
			{
				if (!sortedFieldNames.ContainsKey(fld))
				{
					sortedFieldNames.Add(fld, GetDBFieldName(fld));
				}
				if (String.IsNullOrEmpty(sortedFieldNames[fld])) { return null; }
				sbSortedFields.Append((sbSortedFields.ToString().Trim().Length > 0 ? "," : "") + sortedFieldNames[fld]);
			}

			// Get the datatable
			string sql = string.Empty;
			SqlCommand cmd = null;
			DataTable dt = new DataTable();
			ClassGenExceptionCollection errors = new ClassGenExceptionCollection();

			try
			{
				sql = "SELECT DISTINCT " + sbFields.ToString() + " " +
						"FROM vwSearch_Contact_PhoneList " +
						sbWhereClause.ToString() + " " +
						(!String.IsNullOrEmpty(whereClause) ? "AND (" + whereClause + ") " : "") +
						(!String.IsNullOrEmpty(sbSortedFields.ToString()) ? " ORDER BY " + sbSortedFields.ToString() + "" : "");
				cmd = new SqlCommand(sql);
				dt = DAL.SQLExecDataTable(cmd);
			}
			catch (SqlException sqle) { errors.Add(new ClassGenException(sqle)); }
			catch (Exception ex) { errors.Add(new ClassGenException(ex)); }

			return dt;
		}

		/// <summary>
		/// Get the minimum value based on the elements in a database table.
		/// </summary>
		/// <param name="field">The field type to get.</param>
		/// <returns>The single earliest DateTime from the collection.</returns>
		public static DateTime? GetMinDateFromDB(Search_Contact_PhoneListMinMaxDateField field)
		{
			return GetMinDateFromDB(field, string.Empty);
		}

		/// <summary>
		/// Get the minimum based on the elements in a database table.
		/// </summary>
		/// <param name="field">The field type to get.</param>
		/// <param name="whereClause">The where clause to fire against the database.</param>
		/// <returns>The single earliest DateTime from the collection.</returns>
		public static DateTime? GetMinDateFromDB(Search_Contact_PhoneListMinMaxDateField field, string whereClause)
		{
			Search_Contact_PhoneListField fld = (Search_Contact_PhoneListField)Enum.Parse(typeof(Search_Contact_PhoneListField),
				field.ToString(), true);
			string fldName = GetDBFieldName(fld);

			if (String.IsNullOrEmpty(fldName)) { return null; }

			// Get the datatable
			string sql = string.Empty;
			SqlCommand cmd = null;
			DataTable dt = new DataTable();
			ClassGenExceptionCollection errors = new ClassGenExceptionCollection();

			try
			{
				sql = "SELECT MIN([" + fldName + "]) " +
						"FROM [vwSearch_Contact_PhoneList] " +
						"WHERE [" + fldName + "] IS NOT NULL " +
						(!String.IsNullOrEmpty(whereClause) ? "AND (" + whereClause + ") " : "") +
						"";
				cmd = new SqlCommand(sql);
				dt = DAL.SQLExecDataTable(cmd);
				if (dt.Rows.Count == 0) { return null; }
				return (DateTime)dt.Rows[0][0];		// Return the value
			}
			catch (SqlException sqle) { errors.Add(new ClassGenException(sqle)); }
			catch (Exception ex) { errors.Add(new ClassGenException(ex)); }

			return null;
		}

		/// <summary>
		/// Get the maximum value based on the elements in a database table.
		/// </summary>
		/// <param name="field">The field type to get.</param>
		/// <returns>The single latest DateTime from the collection.</returns>
		public static DateTime? GetMaxDateFromDB(Search_Contact_PhoneListMinMaxDateField field)
		{
			return GetMaxDateFromDB(field, string.Empty);
		}

		/// <summary>
		/// Get the maximum value based on the elements in a database table.
		/// </summary>
		/// <param name="field">The field type to get.</param>
		/// <param name="whereClause">The where clause to fire against the database.</param>
		/// <returns>The single latest DateTime from the collection.</returns>
		public static DateTime? GetMaxDateFromDB(Search_Contact_PhoneListMinMaxDateField field, string whereClause)
		{
			Search_Contact_PhoneListField fld = (Search_Contact_PhoneListField)Enum.Parse(typeof(Search_Contact_PhoneListField),
				field.ToString(), true);
			string fldName = GetDBFieldName(fld);

			if (String.IsNullOrEmpty(fldName)) { return null; }

			// Get the datatable
			string sql = string.Empty;
			SqlCommand cmd = null;
			DataTable dt = new DataTable();
			ClassGenExceptionCollection errors = new ClassGenExceptionCollection();

			try
			{
				sql = "SELECT MAX([" + fldName + "]) " +
						"FROM [vwSearch_Contact_PhoneList] " +
						"WHERE [" + fldName + "] IS NOT NULL " +
						(!String.IsNullOrEmpty(whereClause) ? "AND (" + whereClause + ") " : "") +
						"";
				cmd = new SqlCommand(sql);
				dt = DAL.SQLExecDataTable(cmd);
				if (dt.Rows.Count == 0) { return null; }
				return (DateTime)dt.Rows[0][0];		// Return the value
			}
			catch (SqlException sqle) { errors.Add(new ClassGenException(sqle)); }
			catch (Exception ex) { errors.Add(new ClassGenException(ex)); }

			return null;
		}

		/// <summary>
		/// Get the minimum value based on the elements in a database table.
		/// </summary>
		/// <param name="field">The field type to get.</param>
		/// <returns>The single least value from the collection.</returns>
		public static decimal? GetMinNumberFromDB(Search_Contact_PhoneListMinMaxNumberField field)
		{
			return GetMinNumberFromDB(field, string.Empty);
		}

		/// <summary>
		/// Get the minimum based on the elements in a database table.
		/// </summary>
		/// <param name="field">The field type to get.</param>
		/// <param name="whereClause">The where clause to fire against the database.</param>
		/// <returns>The single least value from the collection.</returns>
		public static decimal? GetMinNumberFromDB(Search_Contact_PhoneListMinMaxNumberField field, string whereClause)
		{
			Search_Contact_PhoneListField fld = (Search_Contact_PhoneListField)Enum.Parse(typeof(Search_Contact_PhoneListField),
				field.ToString(), true);
			string fldName = GetDBFieldName(fld);

			if (String.IsNullOrEmpty(fldName)) { return null; }

			// Get the datatable
			string sql = string.Empty;
			SqlCommand cmd = null;
			DataTable dt = new DataTable();
			ClassGenExceptionCollection errors = new ClassGenExceptionCollection();

			try
			{
				sql = "SELECT MIN([" + fldName + "]) " +
						"FROM [vwSearch_Contact_PhoneList] " +
						"WHERE [" + fldName + "] IS NOT NULL " +
						(!String.IsNullOrEmpty(whereClause) ? "AND (" + whereClause + ") " : "") +
						"";
				cmd = new SqlCommand(sql);
				dt = DAL.SQLExecDataTable(cmd);
				if (dt.Rows.Count == 0) { return null; }
				return (decimal)dt.Rows[0][0];		// Return the value
			}
			catch (SqlException sqle) { errors.Add(new ClassGenException(sqle)); }
			catch (Exception ex) { errors.Add(new ClassGenException(ex)); }

			return null;
		}

		/// <summary>
		/// Get the maximum value based on the elements in a database table.
		/// </summary>
		/// <param name="field">The field type to get.</param>
		/// <returns>The single greatest value from the collection.</returns>
		public static decimal? GetMaxNumberFromDB(Search_Contact_PhoneListMinMaxNumberField field)
		{
			return GetMaxNumberFromDB(field, string.Empty);
		}

		/// <summary>
		/// Get the maximum value based on the elements in a database table.
		/// </summary>
		/// <param name="field">The field type to get.</param>
		/// <param name="whereClause">The where clause to fire against the database.</param>
		/// <returns>The single greatest value from the collection.</returns>
		public static decimal? GetMaxNumberFromDB(Search_Contact_PhoneListMinMaxNumberField field, string whereClause)
		{
			Search_Contact_PhoneListField fld = (Search_Contact_PhoneListField)Enum.Parse(typeof(Search_Contact_PhoneListField),
				field.ToString(), true);
			string fldName = GetDBFieldName(fld);

			if (String.IsNullOrEmpty(fldName)) { return null; }

			// Get the datatable
			string sql = string.Empty;
			SqlCommand cmd = null;
			DataTable dt = new DataTable();
			ClassGenExceptionCollection errors = new ClassGenExceptionCollection();

			try
			{
				sql = "SELECT MAX([" + fldName + "]) " +
						"FROM [vwSearch_Contact_PhoneList] " +
						"WHERE [" + fldName + "] IS NOT NULL " +
						(!String.IsNullOrEmpty(whereClause) ? "AND (" + whereClause + ") " : "") +
						"";
				cmd = new SqlCommand(sql);
				dt = DAL.SQLExecDataTable(cmd);
				if (dt.Rows.Count == 0) { return null; }
				return (decimal)dt.Rows[0][0];		// Return the value
			}
			catch (SqlException sqle) { errors.Add(new ClassGenException(sqle)); }
			catch (Exception ex) { errors.Add(new ClassGenException(ex)); }

			return null;
		}

		/// <summary>
		/// Copy the object - then change the id field to a new value
		/// </summary>
		/// <param name="source">The object to copy.</param>
		/// <returns>A copy of the object, with a new ID.</returns>
		public static Search_Contact_PhoneList CopyFrom(Search_Contact_PhoneList source)
		{
			// Make the copy of the object
			Search_Contact_PhoneList item = source.Clone();
			
			// Change the ID field

			// Reset the record status to new
			item.RecordStatus = RecordStatus.New;

			return item;
		}

		/// <summary>
		/// Convert the passed string into a db friendly string (one that 
		/// doesn't include the names in the object, but rather the names 
		/// from the fields from the database).
		/// </summary>
		/// <param name="dbString">The string to process.</param>
		/// <returns>The converted string.</returns>
		public static string ToDBFriendly(string dbString)
		{
			string rtv = dbString;

			rtv = rtv.Replace("[ContactID]", "[iContactID]");
			rtv = rtv.Replace("[AgencyID]", "[iAgencyID]");
			rtv = rtv.Replace("[LastName]", "[sLastName]");
			rtv = rtv.Replace("[FirstName]", "[sFirstName]");
			rtv = rtv.Replace("[FullName_LastFirst]", "[sFullName_LastFirst]");
			rtv = rtv.Replace("[HomePhone]", "[sHomePhone]");
			rtv = rtv.Replace("[OtherPhone]", "[sOtherPhone]");
			rtv = rtv.Replace("[PagerPhone]", "[sPagerPhone]");
			rtv = rtv.Replace("[CellPhone]", "[sCellPhone]");
			rtv = rtv.Replace("[WorkPhone]", "[sWorkPhone]");

			return rtv;
		}

		#region Json.NET Serialization
		/// <summary>
		/// Attempt to serialize the Search_Contact_PhoneList object to the server
		/// </summary>
		/// <param name="obj">The Search_Contact_PhoneList object to serialize</param>
		/// <returns>A string containing the return from the method</returns>
		public static string SerializeObject(Search_Contact_PhoneList obj)
		{
			string rtv = string.Empty;

			try
			{
				rtv = Newtonsoft.Json.JsonConvert.SerializeObject(obj);
			}
			catch (Exception ex)
			{
				rtv = "Error: " + ex.Message;
			}

			return rtv;         // Return the result
		}

		/// <summary>
		/// Attempt to Deserialize the Search_Contact_PhoneList object from the server
		/// </summary>
		/// <param name="obj">The Search_Contact_PhoneList object to deserialize</param>
		/// <param name="errors">The errors collection</param>
		/// <returns>A Search_Contact_PhoneList object containing the return from the method</returns>
		public static Search_Contact_PhoneList DeserializeObject(string obj, ref ClassGenExceptionCollection errors)
		{
			Search_Contact_PhoneList rtv = null;

			try
			{
				rtv = Newtonsoft.Json.JsonConvert.DeserializeObject<Search_Contact_PhoneList>(obj);
			}
			catch (Exception ex)
			{
				errors.Add(new ClassGenException("Error: " + ex.Message, ClassGenExceptionIconType.Critical));
			}

			return rtv;         // Return the result
		}
		#endregion Json.NET Serialization

		#endregion Public Static Methods

		#region IClassGenPropertyChanging Implementation

		/// <summary>
		/// Occurs when a property is about to change.
		/// </summary>
		public event PropertyChangingEventHandler PropertyChanging;
		/// <summary>
		/// Occurs when a ClassGen property is about to change.
		/// </summary>
		public event ClassGenPropertyChangingEventHandler ClassGenPropertyChanging;
		private bool NotifyPropertyChanging(string info, object oldValue, object newValue)
		{
			bool cancel = false;
			if (ClassGenPropertyChanging != null)
			{
				ClassGenPropertyChangingEventArgs e = new ClassGenPropertyChangingEventArgs(info, oldValue, newValue);
				ClassGenPropertyChanging(this, e);
				cancel = e.Cancel; 
			}
			if (!cancel && PropertyChanging != null)
			{
				PropertyChangingEventArgs e = new PropertyChangingEventArgs(info);
				PropertyChanging(this, e);
			}
			return cancel;
		}

		#endregion IClassGenPropertyChanging Implementation
		
		#region IClassGenLogXML Implementation
		/// <summary>
		/// Gets the current object as an XML object stream.
		/// </summary>
		/// <param name="includeBaseProperties">True to include the base properties 
		///		created as model base objects (GridCustom0-9, etc.).</param>
		/// <returns>The object as an XML string.</returns>
		public string GetAsXML(bool includeBaseProperties)
		{
			StringBuilder sb = new StringBuilder();

			sb.Append("<ContactID>" + System.Security.SecurityElement.Escape(ContactID.ToString()) + "</ContactID>" + Environment.NewLine);
			sb.Append("<AgencyID>" + System.Security.SecurityElement.Escape(AgencyID.ToString()) + "</AgencyID>" + Environment.NewLine);
			sb.Append("<LastName>" + System.Security.SecurityElement.Escape(LastName) + "</LastName>" + Environment.NewLine);
			sb.Append("<FirstName>" + System.Security.SecurityElement.Escape(FirstName) + "</FirstName>" + Environment.NewLine);
			sb.Append("<FullName_LastFirst>" + System.Security.SecurityElement.Escape(FullName_LastFirst) + "</FullName_LastFirst>" + Environment.NewLine);
			sb.Append("<HomePhone>" + System.Security.SecurityElement.Escape(HomePhone) + "</HomePhone>" + Environment.NewLine);
			sb.Append("<OtherPhone>" + System.Security.SecurityElement.Escape(OtherPhone) + "</OtherPhone>" + Environment.NewLine);
			sb.Append("<PagerPhone>" + System.Security.SecurityElement.Escape(PagerPhone) + "</PagerPhone>" + Environment.NewLine);
			sb.Append("<CellPhone>" + System.Security.SecurityElement.Escape(CellPhone) + "</CellPhone>" + Environment.NewLine);
			sb.Append("<WorkPhone>" + System.Security.SecurityElement.Escape(WorkPhone) + "</WorkPhone>" + Environment.NewLine);

			if (includeBaseProperties)
			{
				sb.Append("<RecordStatus>" + this.RecordStatus.ToString() + "</RecordStatus>" + Environment.NewLine);
				sb.Append("<CheckedInGrid>" + this.CheckedInGrid.ToString() + "</CheckedInGrid>" + Environment.NewLine);
				sb.Append("<IsDisposable>" + this.IsDisposable.ToString() + "</IsDisposable>" + Environment.NewLine);

				sb.Append("<GridCustom_0>" + System.Security.SecurityElement.Escape(this.GridCustom_0) + "</GridCustom_0>" + Environment.NewLine);
				sb.Append("<GridCustom_1>" + System.Security.SecurityElement.Escape(this.GridCustom_1) + "</GridCustom_1>" + Environment.NewLine);
				sb.Append("<GridCustom_2>" + System.Security.SecurityElement.Escape(this.GridCustom_2) + "</GridCustom_2>" + Environment.NewLine);
				sb.Append("<GridCustom_3>" + System.Security.SecurityElement.Escape(this.GridCustom_3) + "</GridCustom_3>" + Environment.NewLine);
				sb.Append("<GridCustom_4>" + System.Security.SecurityElement.Escape(this.GridCustom_4) + "</GridCustom_4>" + Environment.NewLine);
				sb.Append("<GridCustom_5>" + System.Security.SecurityElement.Escape(this.GridCustom_5) + "</GridCustom_5>" + Environment.NewLine);
				sb.Append("<GridCustom_6>" + System.Security.SecurityElement.Escape(this.GridCustom_6) + "</GridCustom_6>" + Environment.NewLine);
				sb.Append("<GridCustom_7>" + System.Security.SecurityElement.Escape(this.GridCustom_7) + "</GridCustom_7>" + Environment.NewLine);
				sb.Append("<GridCustom_8>" + System.Security.SecurityElement.Escape(this.GridCustom_8) + "</GridCustom_8>" + Environment.NewLine);
				sb.Append("<GridCustom_9>" + System.Security.SecurityElement.Escape(this.GridCustom_9) + "</GridCustom_9>" + Environment.NewLine);
			}

			if (!String.IsNullOrEmpty(sb.ToString()))
			{
				sb.Insert(0, "<Search_Contact_PhoneList>" + Environment.NewLine);
				sb.Append("</Search_Contact_PhoneList>" + Environment.NewLine);
			}

			return sb.ToString();
		}

		/// <summary>
		/// Get the current object as an XML object stream with all base properties included.
		/// </summary>
		/// <returns>The object as an XML string with all base properties included.</returns>
		public string GetAsXML()
		{
			return GetAsXML(true);
		}

		/// <summary>
		/// Get the changed elements as an XML list of strings.
		/// Strings are broken at 6000 characters.
		/// </summary>
		/// <returns>A string value containing the XML list.</returns>
		public string GetChangedElementsAsXML()
		{
			StringBuilder sb = new StringBuilder();

			// Get the original values in relation to the new ones
			sb.Append("\t<ContactID>");
			sb.Append(ContactID.ToString());
			sb.Append("</ContactID>" + Environment.NewLine);

			sb.Append("\t<AgencyID>");
			sb.Append(AgencyID.ToString());
			sb.Append("</AgencyID>" + Environment.NewLine);

			sb.Append("\t<LastName>");
			sb.Append(LastName);
			sb.Append("</LastName>" + Environment.NewLine);

			sb.Append("\t<FirstName>");
			sb.Append(FirstName);
			sb.Append("</FirstName>" + Environment.NewLine);

			sb.Append("\t<FullName_LastFirst>");
			sb.Append(FullName_LastFirst);
			sb.Append("</FullName_LastFirst>" + Environment.NewLine);

			if (!String.IsNullOrEmpty(sb.ToString()))
			{
				sb.Insert(0, "<Search_Contact_PhoneList>" + Environment.NewLine);
				sb.Append("</Search_Contact_PhoneList>" + Environment.NewLine);
			}

			return sb.ToString();
		}

		/// <summary>
		/// Generates a new Search_Contact_PhoneList object from an XML description.
		/// </summary>
		/// <param name="xml">The string of XML to load from.</param>
		/// <returns>A new Search_Contact_PhoneList object.</returns>
		public static Search_Contact_PhoneList LoadFromXML(string xml)
		{
			Search_Contact_PhoneList item = new Search_Contact_PhoneList();
			System.Xml.XmlDocument doc = new System.Xml.XmlDocument();
			bool propSet = false;
			doc.LoadXml(xml);

			foreach (System.Xml.XmlNode child in doc.ChildNodes[0].ChildNodes)
			{
				if (!propSet) { propSet = true; }
				switch (child.Name)
				{
					case "ContactID": item.ContactID = long.Parse(child.InnerText); break;
					case "AgencyID": item.AgencyID = long.Parse(child.InnerText); break;
					case "LastName": item.LastName = child.InnerText; break;
					case "FirstName": item.FirstName = child.InnerText; break;
					case "FullName_LastFirst": item.FullName_LastFirst = child.InnerText; break;

					case "HomePhone": item.HomePhone = child.InnerText; break;
					case "OtherPhone": item.OtherPhone = child.InnerText; break;
					case "PagerPhone": item.PagerPhone = child.InnerText; break;
					case "CellPhone": item.CellPhone = child.InnerText; break;
					case "WorkPhone": item.WorkPhone = child.InnerText; break;

					case "RecordStatus": item.RecordStatus = (RecordStatus)Enum.Parse(typeof(RecordStatus), child.InnerText, true); break;
					case "CheckedInGrid": item.CheckedInGrid = bool.Parse(child.InnerText); break;
					case "IsDisposable": item.IsDisposable = bool.Parse(child.InnerText); break;
					case "GridCustom_0": item.GridCustom_0 = child.InnerText; break;
					case "GridCustom_1": item.GridCustom_1 = child.InnerText; break;

					case "GridCustom_2": item.GridCustom_2 = child.InnerText; break;
					case "GridCustom_3": item.GridCustom_3 = child.InnerText; break;
					case "GridCustom_4": item.GridCustom_4 = child.InnerText; break;
					case "GridCustom_5": item.GridCustom_5 = child.InnerText; break;
					case "GridCustom_6": item.GridCustom_6 = child.InnerText; break;

					case "GridCustom_7": item.GridCustom_7 = child.InnerText; break;
					case "GridCustom_8": item.GridCustom_8 = child.InnerText; break;
					case "GridCustom_9": item.GridCustom_9 = child.InnerText; break;
				}
			}
			return (propSet ? item : null);
		}
		#endregion IClassGenLogXML Implementation
	}
	#endregion Search_Contact_PhoneList Class

	#region Search_Contact_PhoneListField Enum
	/// <summary>
	/// Enum for each field type in the element.
	/// </summary>
	public enum Search_Contact_PhoneListField
	{
		/// <summary>
		/// The ContactID element.
		/// </summary>
		ContactID,
		/// <summary>
		/// The AgencyID element.
		/// </summary>
		AgencyID,
		/// <summary>
		/// The LastName element.
		/// </summary>
		LastName,
		/// <summary>
		/// The FirstName element.
		/// </summary>
		FirstName,
		/// <summary>
		/// The FullName_LastFirst element.
		/// </summary>
		FullName_LastFirst,
		/// <summary>
		/// The HomePhone element.
		/// </summary>
		HomePhone,
		/// <summary>
		/// The OtherPhone element.
		/// </summary>
		OtherPhone,
		/// <summary>
		/// The PagerPhone element.
		/// </summary>
		PagerPhone,
		/// <summary>
		/// The CellPhone element.
		/// </summary>
		CellPhone,
		/// <summary>
		/// The WorkPhone element.
		/// </summary>
		WorkPhone,
	}
	#endregion Search_Contact_PhoneListField Enum

	#region Search_Contact_PhoneListMinMaxDateField Enum
	/// <summary>
	/// Enum for each DateTime field in the element that can have a minimum or maximum.
	/// </summary>
	public enum Search_Contact_PhoneListMinMaxDateField
	{
	}
	#endregion Search_Contact_PhoneListMinMaxDateField Enum

	#region Search_Contact_PhoneListMinMaxNumberField Enum
	/// <summary>
	/// Enum for each numerical field in the element that can have a minimum or maximum.
	/// </summary>
	public enum Search_Contact_PhoneListMinMaxNumberField
	{
		/// <summary>
		/// The ContactID element.
		/// </summary>
		ContactID,
		/// <summary>
		/// The AgencyID element.
		/// </summary>
		AgencyID,
	}
	#endregion Search_Contact_PhoneListMinMaxNumberField Enum

	#region Search_Contact_PhoneList Collection
	/// <summary>
	/// A collection for Search_Contact_PhoneList objects.
	/// </summary>
	/// <remarks>
	/// This collection class is the primary way to work with Search_Contact_PhoneList objects.
	/// Most of the functionality is in this class, including the methods for creating Search_Contact_PhoneList objects from a database.
	/// </remarks>
	[Serializable]
	public partial class Search_Contact_PhoneListCollection : ClassGenBindingList<Search_Contact_PhoneList, long>, IDisposable, 
		IClassGenLogXMLCollection, IClassGenClassGenerated
	{
		#region Constructors
		/// <summary>
		/// Create an empty collection.
		/// </summary>
		public Search_Contact_PhoneListCollection() 
		{
			// The Key Field Name for the collection
			this.KeyFieldName = "ContactID";

			_rules = new ClassGenRules(this);			// Set the base collection
		}

		/// <summary>
		/// Create a collection and populate it with information based on the where clause.
		/// </summary>
		/// <param name="whereClause">The SQL where clause to use to populate the collection.</param>
		public Search_Contact_PhoneListCollection(string whereClause) 
		{
			// The Key Field Name for the collection
			this.KeyFieldName = "ContactID";

			_rules = new ClassGenRules(this);			// Set the base collection
			this.GetFromDB(whereClause);			// Populate the collection
		}

		/// <summary>
		/// Create a collection and populate it with information based on the where clause.
		/// </summary>
		/// <param name="whereClause">The SQL where clause to use to populate the collection.</param>
		/// <param name="getChildren">True if the collection should populate all child collections as well.</param>
		public Search_Contact_PhoneListCollection(string whereClause, bool getChildren) 
		{
			// The Key Field Name for the collection
			this.KeyFieldName = "ContactID";

			_rules = new ClassGenRules(this);				// Set the base collection
			this.GetFromDB(whereClause, getChildren);		// Populate the collection
		}
		#endregion Constructors

		#region Public Properties

		/// <summary>
		/// A collection of all the active records from the collection (the ones without a status of "Deleted").
		/// </summary>
		public new Search_Contact_PhoneListCollection ActiveRecords
		{
			get
			{
				return (Search_Contact_PhoneListCollection)base.ActiveRecords;
			}
		}

		/// <summary>
		/// A collection of all the deleted records from the collection (the ones with a status of "Deleted").
		/// </summary>
		public Search_Contact_PhoneListCollection DeletedRecords
		{
			get
			{
				return (Search_Contact_PhoneListCollection)GetRecordsBasedOnStatus(RecordStatus.Deleted);
			}
		}

		/// <summary>
		/// A collection of all the modified records from the collection (the ones with a status of "Modified").
		/// </summary>
		public Search_Contact_PhoneListCollection ModifiedRecords
		{
			get
			{
				return (Search_Contact_PhoneListCollection)GetRecordsBasedOnStatus(RecordStatus.Modified);
			}
		}

		/// <summary>
		/// A collection of all the new records from the collection (the ones with a status of "New").
		/// </summary>
		public Search_Contact_PhoneListCollection NewRecords
		{
			get
			{
				return (Search_Contact_PhoneListCollection)GetRecordsBasedOnStatus(RecordStatus.New);
			}
		}

		#endregion Public Properties

		#region Collection Get Methods
		/// <summary>
		/// Populate the collection with items, using the SQL Where clause included.
		/// </summary>
		/// <param name="dbCount">A long variable (passed by reference) where this method can record the count of total records retrieved.</param>
		/// <returns>A collection of any exceptions this method raises.</returns>
		public ClassGenExceptionCollection GetFromDB(ref long dbCount)
		{
			dbCount = Search_Contact_PhoneListCollection.GetCountFromDB();
			return GetFromDB();
		}

		/// <summary>
		/// Populate the collection with items, using the SQL Where clause included.
		/// </summary>
		/// <param name="whereClause">An SQL Where clause to apply to the get.  Do not include the keyword WHERE - this method will add it for you.</param>
		/// <param name="dbCount">A long variable (passed by reference) where this method can record the count of total records retrieved.</param>
		/// <returns>A collection of any exceptions this method raises.</returns>
		public ClassGenExceptionCollection GetFromDB(string whereClause, ref long dbCount)
		{
			this.GetCollectionConfig.WhereClause = whereClause;
			this.GetCollectionConfig.GetChildren = false;
			this.GetCollectionConfig.IncludeUpdateDateInWhereClause = false;
			dbCount = Search_Contact_PhoneListCollection.GetCountFromDB(whereClause);
			return GetFromDB();
		}

		/// <summary>
		/// Populate the collection with items, using the where clause included.
		/// </summary>
		/// <param name="whereClause">An SQL Where clause to apply to the get.  Do not include the keyword WHERE - this method will add it for you.</param>
		/// <param name="getChildren">True if the developer wants all children collections returned as well.</param>
		/// <param name="dbCount">A long variable (passed by reference) where this method can record the count of total records retrieved.</param>
		/// <returns>A collection of any exceptions this method raises.</returns>
		public ClassGenExceptionCollection GetFromDB(string whereClause, bool getChildren, ref long dbCount)
		{
			this.GetCollectionConfig.WhereClause = whereClause;
			this.GetCollectionConfig.GetChildren = getChildren;
			this.GetCollectionConfig.IncludeUpdateDateInWhereClause = false;
			dbCount = Search_Contact_PhoneListCollection.GetCountFromDB(whereClause);
			return GetFromDB();
		}

		/// <summary>
		/// Get all items from the database.
		/// Gets and populates all children objects as well.
		/// </summary>
		/// <returns>A collection of any exceptions this method raises.</returns>
		public ClassGenExceptionCollection GetFromDBWithChildren()
		{
			this.GetCollectionConfig.WhereClause = string.Empty;
			this.GetCollectionConfig.GetChildren = true;
			return GetFromDB();
		}

		/// <summary>
		/// Populate the collection with items, using the Where clause included.
		/// </summary>
		/// <param name="whereClause">An SQL Where clause to apply to the get.  Do not include the keyword WHERE - this method will add it for you.</param>
		/// <returns>A collection of any exceptions this method raises.</returns>
		public ClassGenExceptionCollection GetFromDB(string whereClause)
		{
			this.GetCollectionConfig.WhereClause = whereClause;
			this.GetCollectionConfig.GetChildren = false;
			this.GetCollectionConfig.IncludeUpdateDateInWhereClause = false;
			return GetFromDB();
		}

		/// <summary>
		/// Populate the collection with items, using the Where clause included.
		/// </summary>
		/// <param name="whereClause">An SQL Where clause to apply to the get.  Do not include the keyword WHERE - this method will add it for you.</param>
		/// <param name="getChildren">True if the developer wants all children collections returned as well.</param>
		/// <returns>A collection of any exceptions this method raises.</returns>
		public ClassGenExceptionCollection GetFromDB(string whereClause, bool getChildren)
		{
			this.GetCollectionConfig.WhereClause = whereClause;
			this.GetCollectionConfig.GetChildren = getChildren;
			this.GetCollectionConfig.IncludeUpdateDateInWhereClause = false;
			return GetFromDB();
		}

		/// <summary>
		/// Populate the collection with items, using the Where clause included
		/// </summary>
		/// <returns>A collection of any exceptions this method raises.</returns>
		public ClassGenExceptionCollection GetFromDB() 
		{
			string sql = string.Empty;
			SqlCommand cmd = null;
			DataTable dt = new DataTable();
			SqlParameter param = null;
			ClassGenExceptionCollection errors = new ClassGenExceptionCollection();
			
			// Reset the IsLoaded Variable before we load the collection
			this._isLoaded = false;
			
			// See if we're supposed to get this thing paged
			if (this.GetCollectionConfig.PageRecords)
			{
				_backgroundWorker = new BackgroundWorker();
				_backgroundWorker.WorkerReportsProgress = true;
				_backgroundWorker.WorkerSupportsCancellation = true;
				_backgroundWorker.RunWorkerCompleted += new RunWorkerCompletedEventHandler(_backgroundWorker_RunWorkerCompleted);
				_backgroundWorker.ProgressChanged += new ProgressChangedEventHandler(_backgroundWorker_ProgressChanged);
				_backgroundWorker.DoWork += new DoWorkEventHandler(_backgroundWorker_DoWork);
				_backgroundWorker.RunWorkerAsync();
				return errors;
			}

			try
			{
				sql = "SELECT " + (this.GetCollectionConfig.TopRecords > -1 ? "TOP " + this.GetCollectionConfig.TopRecords.ToString() + " " : "") +
					" [SCPL].*, GETDATE() AS dateTimeObjectPopulated " + 
					"FROM vwSearch_Contact_PhoneList [SCPL] " + 
					(!String.IsNullOrEmpty(this.GetCollectionConfig.WhereClause) ? "WHERE " + this.GetCollectionConfig.WhereClause : "") + 
					"";
				if (this.GetCollectionConfig.IncludeUpdateDateInWhereClause)
				{
					sql += (!String.IsNullOrEmpty(this.GetCollectionConfig.WhereClause) ? " AND" : " WHERE") +
						"  > @p";
					param = new SqlParameter("@p", SqlDbType.DateTime);
					param.Value = _dateTimeObjectPopulated;
				}
				if (this.GetCollectionConfig.TopRecords > -1 &&
					!String.IsNullOrEmpty(this.GetCollectionConfig.TopSort))
				{
					sql += " ORDER BY " + this.GetCollectionConfig.TopSort;
				}
				cmd = new SqlCommand(sql);
				if (this.GetCollectionConfig.IncludeUpdateDateInWhereClause) { cmd.Parameters.Add(param); }

				this.OnMasterPopulate("Search_Contact_PhoneList", "Retrieving Full List Of Search_Contact_PhoneLists", string.Empty);
				dt = DAL.SQLExecDataTable(cmd);

				int count = 0;
				if (!this.GetCollectionConfig.IncludeUpdateDateInWhereClause) { this.Clear(); }
				foreach (DataRow row in dt.Rows)
				{
					// Enumerate through the fields and set up the object
					if (count == 0)
					{
						if (row.Table.Columns.Contains("dateTimeObjectPopulated"))
						{
							_dateTimeObjectPopulated = (DateTime)row["dateTimeObjectPopulated"];
						}
						else
						{
							_dateTimeObjectPopulated = DateTime.Now;
						}
						DAL.EvalNumSecondsLocalMachineBehindServer(_dateTimeObjectPopulated.Value);
					}

					this.OnDetailPopulate("Search_Contact_PhoneList", 
						"Populating Search_Contact_PhoneList: " + (++count).ToString("###,###,###,##0") + " of " + dt.Rows.Count.ToString("###,###,###,##0"), 
						string.Empty, 
						dt.Rows.Count, 
						count);

					#region Fields
					Search_Contact_PhoneList item = new Search_Contact_PhoneList();
					item.Get(row);

					this.Add(item);
					#endregion Fields
				}
				
				dt.Dispose();		// Dispose of the datatable

				this._isLoaded = true;				// Set the IsLoaded Property
			}
			catch (SqlException sqle) { errors.Add(new ClassGenException(sqle)); }
			catch (Exception ex) { errors.Add(new ClassGenException(ex)); }

			return errors;		// Return the errors collection
		}

		/// <summary>
		/// Get a count from the database of the total number of records.
		/// </summary>
		/// <param name="whereClause">The SQL Where clause to use to get the total count.</param>
		/// <returns>The count of records.</returns>
		public static long GetCountFromDB(string whereClause)
		{
			string sql = string.Empty;
			SqlCommand cmd = null;
			DataTable dt = new DataTable();
			int rtv = 0;
			ClassGenExceptionCollection errors = new ClassGenExceptionCollection();

			try
			{
				sql = "SELECT COUNT(*) " +
						"FROM vwSearch_Contact_PhoneList " +
						(!String.IsNullOrEmpty(whereClause) ? "WHERE " + whereClause : "") +
						"";
				cmd = new SqlCommand(sql);
				dt = DAL.SQLExecDataTable(cmd);
				if (dt.Rows.Count > 0 &&
					dt.Rows[0][0] != DBNull.Value)
				{
					rtv = (int)dt.Rows[0][0];
				}
			}
			catch (SqlException sqle) { errors.Add(new ClassGenException(sqle)); }
			catch (Exception ex) { errors.Add(new ClassGenException(ex)); }

			return rtv;
		}

		/// <summary>
		/// Get a count from the database of the total number of records.
		/// </summary>
		/// <returns>The count of records.</returns>
		public static long GetCountFromDB()
		{
			return GetCountFromDB(string.Empty);		// Return the base method
		}
		#endregion Collection Get Methods

		#region Clone/Copy Methods
		/// <summary>
		/// Create an exact copy of all the elements in the collection.
		/// </summary>
		/// <returns>The cloned collection.</returns>
		public new Search_Contact_PhoneListCollection Clone()
		{
			Search_Contact_PhoneListCollection newColl = new Search_Contact_PhoneListCollection();
			newColl.AddRange(base.Clone());
			return newColl;
		}

		/// <summary>
		/// Copy the objects in the collection, creating a new ID for each one of them in the process.
		/// </summary>
		/// <returns>A new Search_Contact_PhoneListCollection.</returns>
		public new Search_Contact_PhoneListCollection CopyWithNewIDs()
		{
			return (Search_Contact_PhoneListCollection)base.CopyWithNewIDs();
		}
		#endregion Clone/Copy Methods

		#region GetDistinct Method(s)
		/// <summary>
		/// Get a distinct list of values based on the elements in the collection.
		/// </summary>
		/// <param name="field">The field type to get.</param>
		/// <returns>A list of values from the collection (sorted by value).</returns>
		public List<string> GetDistinctFromCollection(LEAD.Search_Contact_PhoneListField field)
		{
			if (this.Count == 0) { return new List<string>(); }
			SortedList<string, string> vals = new SortedList<string, string>();

			// Add the elements
			switch (field)
			{
				case LEAD.Search_Contact_PhoneListField.ContactID:
					foreach (Search_Contact_PhoneList item in this)
					{
						if (!String.IsNullOrEmpty(item.ContactID.ToString()) && 
							!vals.ContainsKey(item.ContactID.ToString().Trim())) { vals.Add(item.ContactID.ToString().Trim(), item.ContactID.ToString().Trim()); }
					}
					break;
				case LEAD.Search_Contact_PhoneListField.AgencyID:
					foreach (Search_Contact_PhoneList item in this)
					{
						if (!String.IsNullOrEmpty(item.AgencyID.ToString()) && 
							!vals.ContainsKey(item.AgencyID.ToString().Trim())) { vals.Add(item.AgencyID.ToString().Trim(), item.AgencyID.ToString().Trim()); }
					}
					break;
				case LEAD.Search_Contact_PhoneListField.LastName:
					foreach (Search_Contact_PhoneList item in this)
					{
						if (!String.IsNullOrEmpty(item.LastName) && 
							!vals.ContainsKey(item.LastName.Trim())) { vals.Add(item.LastName.Trim(), item.LastName.Trim()); }
					}
					break;
				case LEAD.Search_Contact_PhoneListField.FirstName:
					foreach (Search_Contact_PhoneList item in this)
					{
						if (!String.IsNullOrEmpty(item.FirstName) && 
							!vals.ContainsKey(item.FirstName.Trim())) { vals.Add(item.FirstName.Trim(), item.FirstName.Trim()); }
					}
					break;
				case LEAD.Search_Contact_PhoneListField.FullName_LastFirst:
					foreach (Search_Contact_PhoneList item in this)
					{
						if (!String.IsNullOrEmpty(item.FullName_LastFirst) && 
							!vals.ContainsKey(item.FullName_LastFirst.Trim())) { vals.Add(item.FullName_LastFirst.Trim(), item.FullName_LastFirst.Trim()); }
					}
					break;
				case LEAD.Search_Contact_PhoneListField.HomePhone:
					foreach (Search_Contact_PhoneList item in this)
					{
						if (!String.IsNullOrEmpty(item.HomePhone) && 
							!vals.ContainsKey(item.HomePhone.Trim())) { vals.Add(item.HomePhone.Trim(), item.HomePhone.Trim()); }
					}
					break;
				case LEAD.Search_Contact_PhoneListField.OtherPhone:
					foreach (Search_Contact_PhoneList item in this)
					{
						if (!String.IsNullOrEmpty(item.OtherPhone) && 
							!vals.ContainsKey(item.OtherPhone.Trim())) { vals.Add(item.OtherPhone.Trim(), item.OtherPhone.Trim()); }
					}
					break;
				case LEAD.Search_Contact_PhoneListField.PagerPhone:
					foreach (Search_Contact_PhoneList item in this)
					{
						if (!String.IsNullOrEmpty(item.PagerPhone) && 
							!vals.ContainsKey(item.PagerPhone.Trim())) { vals.Add(item.PagerPhone.Trim(), item.PagerPhone.Trim()); }
					}
					break;
				case LEAD.Search_Contact_PhoneListField.CellPhone:
					foreach (Search_Contact_PhoneList item in this)
					{
						if (!String.IsNullOrEmpty(item.CellPhone) && 
							!vals.ContainsKey(item.CellPhone.Trim())) { vals.Add(item.CellPhone.Trim(), item.CellPhone.Trim()); }
					}
					break;
				case LEAD.Search_Contact_PhoneListField.WorkPhone:
					foreach (Search_Contact_PhoneList item in this)
					{
						if (!String.IsNullOrEmpty(item.WorkPhone) && 
							!vals.ContainsKey(item.WorkPhone.Trim())) { vals.Add(item.WorkPhone.Trim(), item.WorkPhone.Trim()); }
					}
					break;
			}

			List<string> rtv = new List<string>();
			rtv.AddRange(vals.Keys);
			return rtv;
		}
		#endregion GetDistinct Method(s)

		#region Random Methods
		#region GetLocalChildren Methods
		#endregion GetLocalChildren Methods

		/// <summary>
		/// A collection of all broken rules associated with the collection.
		/// (Includes all the child classes validation as well.)
		/// </summary>
		public ClassGenExceptionCollection BrokenRules
		{
			get 
			{
				ClassGenExceptionCollection exceptions = new ClassGenExceptionCollection();
				foreach (Search_Contact_PhoneList item in this.ActiveRecords)
				{
					ClassGenExceptionCollection exCollection = item.BrokenRules;
					if (exCollection.Count > 0)
					{
						foreach (ClassGenException ex in exCollection)
						{
							ex.RecordIndex = (this.IndexOf(item)) + 1;
						}
						exceptions.AddRange(exCollection);
					}
				}

				exceptions.AddRange(_rules.BrokenRules);

				return exceptions;
			}
		}

		/// <summary>
		/// Gets all the records that don't have a deleted status in the collection
		/// </summary>
		/// <returns>A Search_Contact_PhoneListCollection of current records.</returns>
		public Search_Contact_PhoneListCollection GetCurrent()
		{
			return this.ActiveRecords;
		}

		/// <summary>
		/// Checks to see if the element exists in the collection.
		/// </summary>
		/// <returns>A boolean indicating whether the element exists in the collection.</returns>
		public bool Exists()
		{
			// I would really have liked to have generated the code for you for this method.
			// But again, since you don't have a key field for this class, I can't.  Check 
			// the Constructors section at the top of this document for more information.

			return false;
		}

		/// <summary>
		/// Removes the element from the collection based on the argument passed.
		/// </summary>
		public void Remove()
		{
			// I would really have liked to have generated the code for you for this method.
			// But again, since you don't have a key field for this class, I can't.  Check 
			// the Constructors section at the top of this document for more information.
		}
		
		#region Refresh Collection Methods
		/// <summary>
		/// Refresh the object based on the threshhold of set minutes on the object.
		/// </summary>
		/// <param name="threshHoldInMinutes">The threshhold in minutes that is allowed before a record is marked as "old".</param>
		public ClassGenExceptionCollection RefreshCollection(int threshHoldInMinutes)
		{
			ClassGenExceptionCollection errors = new ClassGenExceptionCollection();

			// Find out how far back you need to go based on the passed threshhold
			if (_dateTimeObjectPopulated == null) { return errors; }
			DateTime currentTime = DAL.GetSQLServerDateTime();
			if (((TimeSpan)currentTime.Subtract(_dateTimeObjectPopulated.Value)).TotalMinutes > threshHoldInMinutes)
			{
				// Force a refresh on the object
				this.GetCollectionConfig.IncludeUpdateDateInWhereClause = true;
				errors.AddRange(this.GetFromDB());
			}

			return errors;		// Return the collection
		}

		/// <summary>
		/// Refresh the object based on the currently set Refresh on the project.
		/// </summary>
		/// <returns>A collection of any exceptions created by refreshing the object.</returns>
		public ClassGenExceptionCollection RefreshCollection()
		{
			return RefreshCollection((int)_refreshRate);
		}

		/// <summary>
		/// Force a Refresh on the object based on the held Primary Key GUID
		/// </summary>
		/// <returns>A collection of any exceptions created by refreshing the object.</returns>
		public ClassGenExceptionCollection RefreshForce()
		{
			ClassGenExceptionCollection errors = new ClassGenExceptionCollection();

			if (_isLoaded)
			{
				this.GetCollectionConfig.IncludeUpdateDateInWhereClause = false;
				errors.AddRange(this.GetFromDB());	// Just do a get on the object
			}
			else
			{
				ClassGenException ex = new ClassGenException("You can't force a refresh on an object where the key field is not set.", ClassGenExceptionIconType.Critical);
			}

			return errors;		// Return the collection
		}
		#endregion Refresh Collection Methods
		#endregion Random Methods

		#region DataTable Methods
		/// <summary>
		/// Converts the object to a datatable. 
		/// Does not include deleted records. 
		/// </summary>
		/// <returns>The object as a DataTable.</returns>
		public DataTable ToDataTable()
		{
			return ToDataTable(false);
		}

		/// <summary>
		/// Converts the object to a datatable. 
		/// </summary>
		/// <param name="includeDeleted">Whether to include deleted records in the datatable.</param>
		/// <returns>The object as a DataTable.</returns>
		public DataTable ToDataTable(bool includeDeleted)
		{
			// Generate the datatable object first
			DataTable dt = this.ToEmptyDataTable();

			// Now, go through and build the data table with actual rows
			int count = 0;
			foreach (Search_Contact_PhoneList item in this)
			{
				if (item.RecordStatus == RecordStatus.Current ||
					item.RecordStatus == RecordStatus.Modified ||
					item.RecordStatus == RecordStatus.New ||
					(item.RecordStatus == RecordStatus.Deleted && includeDeleted))
				{
					dt.Rows.Add(item.ToDataRow(dt));
					this.OnDataTablePopulate(string.Empty, string.Empty, string.Empty, this.Count, count + 1);
				}
				count++;
			}
			
			// Return the data table
			return dt;
		}

		/// <summary>
		/// Creates an empty datatable with the object's structure.
		/// </summary>
		/// <returns>An empty DataTable with the object's structure.</returns>
		public DataTable ToEmptyDataTable()
		{
			// Return the data table
			return EmptyDataTableWithIL<Search_Contact_PhoneList>();
		}

		/// <summary>
		/// Event Handler to deal with populating the information
		/// </summary>
		public delegate void DataTablePopulateEventHandler(object sender, PopulateUpdateDelete_EventArgs e);
		/// <summary>
		/// Occurs when this class populates a DataTable with a row of its data.
		/// </summary>
		public event DataTablePopulateEventHandler DataTablePopulate;
		/// <summary>
		/// Calls the DataTable.Populate event.
		/// </summary>
		/// <param name="name">The name of the record in the DataRow.</param>
		/// <param name="description">A description of the record.</param>
		/// <param name="errors">The names of any exceptions that cropped up.</param>
		/// <param name="totalCount">The total number of rows in the DataTable.</param>
		/// <param name="currentIndex">The current Index the iterator has reached.</param>
		protected void OnDataTablePopulate(string name, string description, string errors, int totalCount, int currentIndex)
		{
			if (DataTablePopulate != null)
			{
				PopulateUpdateDelete_EventArgs e = new PopulateUpdateDelete_EventArgs(name, description, errors, totalCount, currentIndex);
				DataTablePopulate(this, e);
			}
		}
		#endregion DataTable Methods

		#region Static Methods
		/// <summary>
		/// Delete records from the table based on a given criteria.
		/// </summary>
		/// <remarks>
		/// The Where clause cannot be empty.
		/// To delete all the records from the table, use the LEADBaseObject.DeleteAll() method, instead.
		/// </remarks>
		/// <param name="whereClause">The SQL where clause to use on the system.</param>
		/// <param name="errors">A ClassGenExceptionCollection to add any exception reports to.</param>
		/// <returns>The number of records affected by the delete.</returns>
		public static int Delete(string whereClause, ref ClassGenExceptionCollection errors)
		{
			string sql = string.Empty;
			SqlCommand cmd = null;
			int recsAffected = 0;

			if (String.IsNullOrEmpty(whereClause))
			{
				errors.Add(new ClassGenException("The where clause cannot be empty.  " + 
					"If you want to delete all records in the table, please call " + 
					"the LEADBaseObject.DeleteAll() method.", ClassGenExceptionIconType.Critical));
				return -1;
			}

			try
			{
				sql = "DELETE FROM vwSearch_Contact_PhoneList " +
					"WHERE " + whereClause.Trim();
				cmd = new SqlCommand(sql);
				recsAffected = DAL.SQLExecNonQuery(cmd);
			}
			catch (SqlException sqle) { errors.Add(new ClassGenException(sqle)); }
			catch (Exception ex) { errors.Add(new ClassGenException(ex)); }

			return recsAffected;
		}
		#endregion Static Methods

		#region Json.NET Serialization Methods
		/// <summary>
		/// Attempt to serialize the Search_Contact_PhoneListCollection object to the server
		/// </summary>
		/// <param name="obj">The Search_Contact_PhoneListCollection object to serialize</param>
		/// <returns>A string containing the return from the method</returns>
		public static string SerializeObject(Search_Contact_PhoneListCollection obj)
		{
			string rtv = string.Empty;

			try
			{
				rtv = Newtonsoft.Json.JsonConvert.SerializeObject(obj);
			}
			catch (Exception ex)
			{
				rtv = "Error: " + ex.Message;
			}

			return rtv;         // Return the result
		}

		/// <summary>
		/// Attempt to Deserialize the Search_Contact_PhoneListCollection object from the server
		/// </summary>
		/// <param name="obj">The Search_Contact_PhoneListCollection object to deserialize</param>
		/// <param name="errors">The errors collection</param>
		/// <returns>A Search_Contact_PhoneListCollection object containing the return from the method</returns>
		public static Search_Contact_PhoneListCollection DeserializeObject(string obj, ref ClassGenExceptionCollection errors)
		{
			Search_Contact_PhoneListCollection rtv = null;

			try
			{
				rtv = Newtonsoft.Json.JsonConvert.DeserializeObject<Search_Contact_PhoneListCollection>(obj);
			}
			catch (Exception ex)
			{
				errors.Add(new ClassGenException("Error: " + ex.Message, ClassGenExceptionIconType.Critical));
			}

			return rtv;         // Return the result
		}
		#endregion Json.NET Serialization Methods

		#region Threaded Get
		private void _backgroundWorker_DoWork(object sender, DoWorkEventArgs e)
		{
			_asyncConnection = DAL.OpenConnection();

			// Create the temp table on the connection
			string sql = string.Empty;
			SqlCommand cmd = null;
			DataTable dt = new DataTable();

			sql = 
				"IF object_id('tempdb..#Search_Contact_PhoneList') IS NOT NULL  DROP TABLE #Search_Contact_PhoneList; " + 
					"CREATE TABLE #Search_Contact_PhoneList (iContactID bigint, iItemIndex INT IDENTITY(1,1) PRIMARY KEY CLUSTERED);  " + 
					"INSERT INTO #Search_Contact_PhoneList (iContactID) SELECT iContactID FROM vwSearch_Contact_PhoneList" + 
					(!String.IsNullOrEmpty(this.GetCollectionConfig.WhereClause) ? " WHERE " + this.GetCollectionConfig.WhereClause : "") + ";  " + 
					"SELECT COUNT(*) AS iCount FROM #Search_Contact_PhoneList "; 
			cmd = new SqlCommand(sql);
			dt = DAL.SQLExecDataTable(cmd, _asyncConnection);

			int totalCount = int.Parse(dt.Rows[0][0].ToString());		// Get the count of records in the table

			BackgroundWorker worker = sender as BackgroundWorker;
			GetAsync(worker, e, _asyncConnection, totalCount, this.GetCollectionConfig.PageSize);		// Start the work
		}

		private void _backgroundWorker_ProgressChanged(object sender, ProgressChangedEventArgs e)
		{
			if (e.UserState != null)
			{
				Search_Contact_PhoneListCollection_GetAsyncObject obj = (Search_Contact_PhoneListCollection_GetAsyncObject)e.UserState;
				this.OnGetThreadedProgress(obj.CurrentIndex, obj.TotalCount, obj.Search_Contact_PhoneListCollection);
			}
		}

		private void _backgroundWorker_RunWorkerCompleted(object sender, RunWorkerCompletedEventArgs e)
		{
			DAL.CloseConnection(_asyncConnection);		// Close the connection
			this.OnGetThreadedCompleted();
			this.IsLoaded = true;		// Set the IsLoaded flag
		}

		/// <summary>
		/// The method that actually does the async Get
		/// </summary>
		private void GetAsync(BackgroundWorker worker, 
			DoWorkEventArgs e, 
			SqlConnection oConn, 
			int totalCount,
			int pageSize)
		{
			int currentIndex = 0, pageStart = 0, pageEnd = 0;
			decimal totalMilleseconds = 0;

			DateTime lastGetStart = DateTime.Now;

			string sql = string.Empty;
			SqlCommand cmd = null;
			DataTable dt = new DataTable();

			Search_Contact_PhoneListCollection coll = new Search_Contact_PhoneListCollection();
			Search_Contact_PhoneList item = new Search_Contact_PhoneList();

			if (worker.CancellationPending) { e.Cancel = true; }		// Cancel the worker if need be

			// Run the method as long as we have records
			while (currentIndex < totalCount)
			{
				sql = string.Empty;  cmd = null;  dt = new DataTable();

				pageStart = currentIndex + 1;
				pageEnd = pageStart - 1 + pageSize;

				sql = "SELECT [SCPL].*, GETDATE() AS dateTimeObjectPopulated " + 
					"FROM vwSearch_Contact_PhoneList [SCPL] " + 
					"INNER JOIN #Search_Contact_PhoneList TEMP ON [SCPL].[iContactID] = [TEMP].[iContactID] " +
					"WHERE TEMP.iItemIndex BETWEEN @piStart AND @piEnd " +
					"";
				cmd = new SqlCommand(sql);
				cmd.Parameters.Add("@piStart", SqlDbType.Int).Value = pageStart;
				cmd.Parameters.Add("@piEnd", SqlDbType.Int).Value = pageEnd;
				lastGetStart = DateTime.Now;
				dt = DAL.SQLExecDataTable(cmd, oConn);

				// Populate the local Search_Contact_PhoneList collection
				coll = new Search_Contact_PhoneListCollection();
				foreach (DataRow row in dt.Rows)
				{
					item = new Search_Contact_PhoneList();
					item.Get(row);
					coll.Add(item);
				}

				currentIndex += dt.Rows.Count;		// The current Index count of where we are in the set

				// Report the progress
				Search_Contact_PhoneListCollection_GetAsyncObject obj = new Search_Contact_PhoneListCollection_GetAsyncObject(currentIndex,
					totalCount, 
					coll);
				worker.ReportProgress((int)(currentIndex / totalCount), obj);

				// Reset the page size based on the number of records pulled back
				totalMilleseconds = (decimal)((TimeSpan)DateTime.Now.Subtract(lastGetStart)).TotalMilliseconds;
				if ((totalMilleseconds < 300 ||
					totalMilleseconds > 700) &&
					totalMilleseconds > 0)
				{
					// Redo the math on the page size to get it within 500 milleseconds
					pageSize = ((500 * pageSize) / (int)totalMilleseconds);
				}

				if (worker.CancellationPending) { e.Cancel = true; }		// Cancel the worker if need be
			}
		}

		// Events to raise as part of population thread
		/// <summary>
		/// The delegate for the GetThreadedProgress event.
		/// </summary>
		public delegate void GetThreadedProgressEventHandler(object sender, Search_Contact_PhoneList_GetCollection_EventArgs e);
		/// <summary>
		/// Occurs when the main thread calls an asynchronous thread to check on its progress getting data from a database.
		/// </summary>
		public event GetThreadedProgressEventHandler GetThreadedProgress;
		/// <summary>
		/// Calls the GetThreadedProgress event.
		/// </summary>
		public void OnGetThreadedProgress(int currentIndex, int totalCount, Search_Contact_PhoneListCollection coll)
		{
			if (GetThreadedProgress != null)
			{
				// Add the items found in the collection to the current set
				foreach (Search_Contact_PhoneList a in coll)
				{
					this.Add(a);		// Add the Search_Contact_PhoneList
				}

				Search_Contact_PhoneList_GetCollection_EventArgs e = new Search_Contact_PhoneList_GetCollection_EventArgs(currentIndex, totalCount, coll);
				GetThreadedProgress(this, e);
			}
		}

		/// <summary>
		/// The delegate for the GetThreadedCompleted event.
		/// </summary>
		public delegate void GetThreadedCompletedEventHandler(object sender, EventArgs e);
		/// <summary>
		/// Occurs when an asynchronous thread finishes getting data from a database.
		/// </summary>
		public event GetThreadedCompletedEventHandler GetThreadedCompleted;
		/// <summary>
		/// Calls the GetThreadedCompleted event.
		/// </summary>
		public void OnGetThreadedCompleted()
		{
			if (GetThreadedCompleted != null)
			{
				EventArgs e = new EventArgs();
				GetThreadedCompleted(this, e);
			}
		}

		/// <summary>
		/// Start the Get All Method in a threaded fashion
		/// </summary>
		/// <param name="pageSize">The number of records to a page.</param>
		/// <param name="whereClause">An SQL Where clause determining which records to get.</param>
		public void GetFromDBThreaded(int pageSize, string whereClause)
		{
			this.GetCollectionConfig.WhereClause = whereClause;
			this.GetCollectionConfig.PageSize = pageSize;
			this.GetCollectionConfig.PageRecords = true;
			GetFromDB();
		}

		/// <summary>
		/// Start the Get All Method in a threaded fashion
		/// </summary>
		/// <param name="whereClause">An SQL Where clause determining which records to get.</param>
		public void GetFromDBThreaded(string whereClause)
		{
			this.GetCollectionConfig.WhereClause = whereClause;
			this.GetCollectionConfig.PageRecords = true;
			GetFromDB();
		}

		/// <summary>
		/// Start the Get All Method in a threaded fashion
		/// </summary>
		/// <param name="pageSize">The number of records to a page.</param>
		public void GetFromDBThreaded(int pageSize)
		{
			this.GetCollectionConfig.PageSize = pageSize;
			this.GetCollectionConfig.PageRecords = true;
			GetFromDB();
		}

		/// <summary>
		/// Start the Get All Method in a threaded fashion
		/// </summary>
		public void GetFromDBThreaded()
		{
			this.GetCollectionConfig.PageRecords = true;
			GetFromDB();
		}

		/// <summary>
		/// Stop the Background worker from getting anymore
		/// </summary>
		public void GetFromDBThreadedStop()
		{
			_backgroundWorker.CancelAsync();
		}
		#endregion Threaded Get

		#region IClassGenLogXMLCollection Implementation
		/// <summary>
		/// Get the collection as an XML Stream with all base model properties included.
		/// </summary>
		/// <returns>The XML Stream.</returns>
		public string GetAsXML()
		{
			return GetAsXML(true);
		}

		/// <summary>
		/// Get the collection as an XML Stream.
		/// </summary>
		/// <param name="includeBaseProperties">True to include the base model properties.</param>
		/// <returns>The XML Stream.</returns>
		public string GetAsXML(bool includeBaseProperties)
		{
			StringBuilder sb = new StringBuilder();
			foreach (Search_Contact_PhoneList item in this)
			{
				sb.Append(item.GetAsXML(includeBaseProperties));
			}

			// Include the header/footer for the stream
			sb.Insert(0, "<Search_Contact_PhoneListCollection>" + Environment.NewLine);
			sb.Append("</Search_Contact_PhoneListCollection>" + Environment.NewLine);

			return sb.ToString();
		}

		/// <summary>
		/// Get the read elements as an XML list of strings.
		/// Strings are broken at 6000 characters.
		/// </summary>
		/// <param name="newElements">A List&lt;&gt; of strings (passed by reference) into which the method can insert elements marked as "new".</param>
		/// <param name="readElements">A List&lt;&gt; of strings (passed by reference) into which the method can insert elements marked as "read".</param>
		/// <param name="changedElements">A List&lt;&gt; of strings (passed by reference) into which the method can insert elements marked as "changed".</param>
		/// <param name="deletedElements">A List&lt;&gt; of strings (passed by reference) into which the method can insert elements marked as "deleted".</param>
		public void GetXMLChanges(ref List<string> newElements,
			ref List<string> readElements,
			ref List<string> changedElements,
			ref List<string> deletedElements)
		{
			StringBuilder sbNew = new StringBuilder(LEAD_BaseObject.SplitOnXMLHeader);
			StringBuilder sbRead = new StringBuilder(LEAD_BaseObject.SplitOnXMLHeader);
			StringBuilder sbChanged = new StringBuilder(LEAD_BaseObject.SplitOnXMLHeader);
			StringBuilder sbDeleted = new StringBuilder(LEAD_BaseObject.SplitOnXMLHeader);

			// Clear out the collections
			newElements = new List<string>();
			readElements = new List<string>();
			changedElements = new List<string>();
			deletedElements = new List<string>();

			// Go through the records and take care of them
			foreach (Search_Contact_PhoneList item in this)
			{
				switch (item.RecordStatus)
				{
					case RecordStatus.Current:
						// Don't forget the to string
						sbRead.Append("<Search_Contact_PhoneList>" + Environment.NewLine);
						sbRead.Append("\t<ContactID>" + item.ContactID.ToString() + "</ContactID>" + Environment.NewLine);
						sbRead.Append("\t<AgencyID>" + item.AgencyID.ToString() + "</AgencyID>" + Environment.NewLine);
						sbRead.Append("\t<LastName>" + (item.LastName != null ? item.LastName : "NULL") + "</LastName>" + Environment.NewLine);
						sbRead.Append("\t<FirstName>" + (item.FirstName != null ? item.FirstName : "NULL") + "</FirstName>" + Environment.NewLine);
						sbRead.Append("\t<FullName_LastFirst>" + (item.FullName_LastFirst != null ? item.FullName_LastFirst : "NULL") + "</FullName_LastFirst>" + Environment.NewLine);
						sbRead.Append("</Search_Contact_PhoneList>" + Environment.NewLine);

						if (sbRead.ToString().Trim().Length > LEAD_BaseObject.SplitOnXMLCharactersForLogging) 
						{ 
							readElements.Add(sbRead.ToString());
							sbRead = new StringBuilder(LEAD_BaseObject.SplitOnXMLHeader); 
						}
						break;

					case RecordStatus.Deleted:
						sbDeleted.Append("<Search_Contact_PhoneList>" + Environment.NewLine);
						sbDeleted.Append("\t<ContactID>" + item.ContactID.ToString() + "</ContactID>" + Environment.NewLine);
						sbDeleted.Append("\t<AgencyID>" + item.AgencyID.ToString() + "</AgencyID>" + Environment.NewLine);
						sbDeleted.Append("\t<LastName>" + (item.LastName != null ? item.LastName : "NULL") + "</LastName>" + Environment.NewLine);
						sbDeleted.Append("\t<FirstName>" + (item.FirstName != null ? item.FirstName : "NULL") + "</FirstName>" + Environment.NewLine);
						sbDeleted.Append("\t<FullName_LastFirst>" + (item.FullName_LastFirst != null ? item.FullName_LastFirst : "NULL") + "</FullName_LastFirst>" + Environment.NewLine);
						sbDeleted.Append("</Search_Contact_PhoneList>" + Environment.NewLine);

						if (sbDeleted.ToString().Trim().Length > LEAD_BaseObject.SplitOnXMLCharactersForLogging)
						{
							deletedElements.Add(sbDeleted.ToString());
							sbDeleted = new StringBuilder(LEAD_BaseObject.SplitOnXMLHeader);
						}
						break;

					case RecordStatus.New:
						sbNew.Append("<Search_Contact_PhoneList>" + Environment.NewLine);
						sbNew.Append("\t<ContactID>" + item.ContactID.ToString() + "</ContactID>" + Environment.NewLine);
						sbNew.Append("\t<AgencyID>" + item.AgencyID.ToString() + "</AgencyID>" + Environment.NewLine);
						sbNew.Append("\t<LastName>" + (item.LastName != null ? item.LastName : "NULL") + "</LastName>" + Environment.NewLine);
						sbNew.Append("\t<FirstName>" + (item.FirstName != null ? item.FirstName : "NULL") + "</FirstName>" + Environment.NewLine);
						sbNew.Append("\t<FullName_LastFirst>" + (item.FullName_LastFirst != null ? item.FullName_LastFirst : "NULL") + "</FullName_LastFirst>" + Environment.NewLine);
						sbNew.Append("</Search_Contact_PhoneList>" + Environment.NewLine);

						if (sbNew.ToString().Trim().Length > LEAD_BaseObject.SplitOnXMLCharactersForLogging)
						{
							newElements.Add(sbNew.ToString());
							sbNew = new StringBuilder(LEAD_BaseObject.SplitOnXMLHeader);
						}
						break;

					case RecordStatus.Modified:
						sbChanged.Append(item.GetChangedElementsAsXML() + Environment.NewLine);

						if (sbChanged.ToString().Trim().Length > LEAD_BaseObject.SplitOnXMLCharactersForLogging)
						{
							changedElements.Add(sbChanged.ToString());
							sbChanged = new StringBuilder(LEAD_BaseObject.SplitOnXMLHeader);
						}
						break;

				}
			}

			// Add the final strings to the list
			newElements.Add(sbNew.ToString());
			readElements.Add(sbRead.ToString());
			deletedElements.Add(sbDeleted.ToString());
			changedElements.Add(sbChanged.ToString());
		}

		/// <summary>
		/// Load the XML into a collection based on what's passed in.
		/// </summary>
		/// <param name="xml">The XML to process.</param>
		/// <returns>The completed Search_Contact_PhoneListCollection object.</returns>
		public static Search_Contact_PhoneListCollection LoadFromXML(string xml)
		{
			Search_Contact_PhoneListCollection coll = new Search_Contact_PhoneListCollection();
			System.Xml.XmlDocument doc = new System.Xml.XmlDocument();
			doc.LoadXml(xml);
			// <Search_Contact_PhoneListCollection>
			foreach (System.Xml.XmlNode nodeMain in doc.ChildNodes)
			{
				// <Search_Contact_PhoneList>
				foreach (System.Xml.XmlNode node in nodeMain.ChildNodes)
				{
					// These are the elements <DetailGUID>, <UserName>, etc.
					Search_Contact_PhoneList item = Search_Contact_PhoneList.LoadFromXML(node.OuterXml);
					if (item != null) { coll.Add(item); }
				}
			}
			return coll;
		}
		#endregion IClassGenLogXMLCollection Implementation

		#region Collection Disposal
		/// <summary>
		/// Implement IDisposable.
		/// Do not make this method virtual.
		/// A derived class should not be able to override this method.
		/// </summary>
		public void Dispose()
		{
			if (!this.IsDisposable) { return; }

			Dispose(true);

			// Take yourself off the Finalization queue 
			// to prevent finalization code for this object
			// from executing a second time.
			GC.SuppressFinalize(this);
		}

		/// <summary>
		/// Dispose(bool disposing) executes in two distinct scenarios.
		/// If disposing equals true, the method has been called directly
		/// or indirectly by a user's code. Managed and unmanaged resources
		/// can be disposed.
		/// If disposing equals false, the method has been called by the 
		/// runtime from inside the finalizer and you should not reference 
		/// other objects. Only unmanaged resources can be disposed.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (!this.IsDisposable) { return; }

			// Check to see if Dispose has already been called.
			if (!this._disposed)
			{
				// Set the disposed on this object to true
				this._disposed = true;

				// If disposing equals true, dispose all managed 
				// and unmanaged resources.
				if (disposing)
				{
					// Dispose managed resources.
					if (_backgroundWorker != null) { _backgroundWorker.Dispose(); _backgroundWorker = null; } 
					GetCollectionConfig = null;
					if (_rules != null) { _rules.Clear(); _rules = null; }
					if (_asyncConnection != null) { _asyncConnection.Dispose(); _asyncConnection = null; }

					// Go through and properly dispose of each object
					foreach (Search_Contact_PhoneList item in this)
					{
						if (item.IsDisposable) { item.Dispose(); }
					}

					// Clear out the collection
					this.Clear();
				}
				// Release unmanaged resources. If disposing is false, 
				// only the following code is executed.
				// <Enter Disposal here> 
				// Note that this is not thread safe.
				// Another thread could start disposing the object
				// after the managed resources are disposed,
				// but before the disposed flag is set to true.
				// If thread safety is necessary, it must be
				// implemented by the client.
			}
		}

		/// <summary>
		/// Use C# destructor syntax for finalization code.
		/// This destructor will run only if the Dispose method 
		/// does not get called.
		/// It gives your base class the opportunity to finalize.
		/// Do not provide destructors in types derived from this class.
		/// </summary>
		~Search_Contact_PhoneListCollection()
		{
			if (!this.IsDisposable) { return; }

			// Do not re-create Dispose clean-up code here.
			// Calling Dispose(false) is optimal in terms of
			// readability and maintainability.
			Dispose(false);
		}
		#endregion Collection Disposal
	}
	#endregion Search_Contact_PhoneList Collection

	#region Event Handler for Async Object
	/// <summary>
	/// Custom class for Search_Contact_PhoneList event args such as population
	/// </summary>
	[Serializable]
	public class Search_Contact_PhoneList_GetCollection_EventArgs : EventArgs
	{
		private int _totalCount = 0;
		private int _currentIndex = 0;
		private Search_Contact_PhoneListCollection _coll = new Search_Contact_PhoneListCollection();

		/// <summary>
		/// Creates a new Search_Contact_PhoneList_GetCollection_EventArgs with the specified properties.
		/// </summary>
		/// <param name="currentIndex">The index of the current record being populated.</param>
		/// <param name="totalCount">The total number of records to be collected.</param>
		/// <param name="coll">The collection holding the records.</param>
		public Search_Contact_PhoneList_GetCollection_EventArgs(int currentIndex, int totalCount, Search_Contact_PhoneListCollection coll)
		{
			_totalCount = totalCount;
			_currentIndex = currentIndex;
			_coll = coll;
		}

		/// <summary>
		/// Creates a new empty Search_Contact_PhoneList_GetCollection_EventArgs.
		/// </summary>
		public Search_Contact_PhoneList_GetCollection_EventArgs()
		{
		}

		/// <summary>
		/// The total number of records to be collected.
		/// </summary>
		public int TotalCount
		{
			get { return _totalCount; }
		}

		/// <summary>
		/// The index of the current record being populated.
		/// </summary>
		public int CurrentIndex
		{
			get { return _currentIndex; }
		}

		/// <summary>
		/// The collection holding the records.
		/// </summary>
		public Search_Contact_PhoneListCollection Search_Contact_PhoneListCollection
		{
			get { return _coll; }
		}
	}
	#endregion Event Handler for Async Object

	#region Async Object for the Threaded Get
	/// <summary>
	/// An object to populate a Search_Contact_PhoneListCollection asynchronously.
	/// </summary>
	public class Search_Contact_PhoneListCollection_GetAsyncObject
	{
		private int _currentIndex = 0;
		private int _totalCount = 0;
		private Search_Contact_PhoneListCollection _coll = new Search_Contact_PhoneListCollection();

		/// <summary>
		/// Creates a new Search_Contact_PhoneList_GetAsyncObject with the specified properties.
		/// </summary>
		/// <param name="currentIndex">The index of the current record to be populated.</param>
		/// <param name="totalCount">The total number of records to be collected.</param>
		/// <param name="coll">The collection holding the records.</param>
		public Search_Contact_PhoneListCollection_GetAsyncObject(int currentIndex, int totalCount, Search_Contact_PhoneListCollection coll)
		{
			_currentIndex = currentIndex;
			_totalCount = totalCount;
			_coll = coll;
		}

		/// <summary>
		/// The index of the current record being populated.
		/// </summary>
		public int CurrentIndex
		{
			get { return _currentIndex; }
		}

		/// <summary>
		/// The total number of records to be collected.
		/// </summary>
		public int TotalCount
		{
			get { return _totalCount; }
		}

		/// <summary>
		/// The collection holding the records.
		/// </summary>
		public Search_Contact_PhoneListCollection Search_Contact_PhoneListCollection
		{
			get { return _coll; }
		}
	}
	#endregion Async Object for the Threaded Get

}

