using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.SqlClient;
using System.Reflection;
using System.Text;

using LEADBase;

namespace LEAD_Log
{
	/// <summary>
	/// Class Name: LogSystem
	/// This class can be modified by the user and will not be written over if the class is already found.
	/// Generated by GenClasses on 01/29/2017 03:52 PM
	/// </summary>
	public partial class LogSystem
	{
		/// <summary>
		/// Create a log entry in the system
		/// </summary>
		/// <param name="eventType">The event type</param>
		/// <param name="msg">The message to log</param>
		/// <returns>An error collection with anything found</returns>
		public static ClassGenExceptionCollection CreateLogEntry(SystemEventType eventType, string msg)
		{
			ClassGenExceptionCollection errors = new ClassGenExceptionCollection();

			// Generate a log entry
			LogSystem item = new LogSystem();
			item.DateLogged = DateTime.Now;
			item.EventType = eventType.ToString();
			item.Message = msg;
			errors = item.AddUpdate();

			return errors;
		}
	}

	public partial class LogSystemCollection : ClassGenBindingList<LogSystem, long>
	{
	}
}

