using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.SqlClient;
using System.Reflection;
using System.Text;

using LEADBase;

namespace LEAD_Log
{
	/// <summary>
	/// Class Name: LogTrans
	/// This class can be modified by the user and will not be written over if the class is already found.
	/// Generated by GenClasses on 01/29/2017 03:52 PM
	/// </summary>
	public partial class LogTrans
	{
	}

	public partial class LogTransCollection : ClassGenBindingList<LogTrans, string>
	{
	}
}

